{{ if get .packages "external" -}}
{{- range .packages.external }}
{{ .target | quote }}:
  {{- .config | toYaml | trim | nindent 2 | replace "$platform" ($.chezmoi.os | replace "darwin" "macos") }}
{{- end }}

{{ end -}}

{{ if .ssh.keysUrl -}}
.ssh/authorized_keys:
  type: file
  url: {{ .ssh.keysUrl | quote }}
  private: true
  refreshPeriod: 24h

{{ end -}}

{{ if .configure.vim -}}
.vim/autoload/plug.vim:
  type: file
  url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  refreshPeriod: 168h

{{ end -}}

{{ if .configure.tmux -}}
.tmux/plugins/tpm:
  type: archive
  url: https://github.com/tmux-plugins/tpm/archive/master.tar.gz
  stripComponents: 1
  exact: true
  refreshPeriod: 168h

{{ end -}}

{{ if .configure.ranger -}}
.config/ranger/plugins/ranger_devicons:
  type: archive
  url: https://github.com/alexanderjeurissen/ranger_devicons/archive/main.tar.gz
  stripComponents: 1
  exact: true
  refreshPeriod: 168h

{{ end -}}

