{{ if .binaries.vim -}}
.vim/autoload/plug.vim:
  type: file
  url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  refreshPeriod: 168h

{{ end -}}

{{ if .binaries.tmux -}}
.tmux/plugins/tpm:
  type: archive
  url: https://github.com/tmux-plugins/tpm/archive/master.tar.gz
  stripComponents: 1
  exact: true
  refreshPeriod: 168h

{{ end -}}

{{ if .binaries.ranger -}}
.config/ranger/plugins/ranger_devicons:
  type: archive
  url: https://github.com/alexanderjeurissen/ranger_devicons/archive/main.tar.gz
  stripComponents: 1
  exact: true
  refreshPeriod: 168h

{{ end -}}

